import subprocess
import os
envvars = os.environ.copy()
envvars["CUDA_VISIBLE_DEVICES"] = "0"
envvars["LD_LIBRARY_PATH"] = f"{envvars['CONDA_PREFIX']}/lib"

# cmd_tokens = ['/home/grl/repo/micromamba/envs/py38/bin/python', '/home/grl/repo/RobotsMakingRobots/legged_env/envs/train.py', 'task=RobotDog', 'test=True', 'num_envs=2', '', "task.env.urdfAsset.file='RobotDog_top-y-7_bottom-y-2.urdf'", "++task.env.urdfAsset.root='/home/grl/repo/RobotsMakingRobots/evolutionary_loop/RobotDog/Offspring/RobotDog_top-y-7_bottom-y-2'", 'task.env.baseHeightTarget=0.2794540557861328', 'task.env.baseInitState.pos=[0,0,0.2794540557861328]', 'task.env.baseInitState.rot=[0,0,0,1]', 'task.env.defaultJointAngles.joint_1_0=0', 'task.env.defaultJointAngles.joint_1_1=0', 'task.env.defaultJointAngles.joint_1_2=0', 'task.env.defaultJointAngles.joint_1_3=0', 'task.env.defaultJointAngles.joint_2_0=0', 'task.env.defaultJointAngles.joint_2_1=0', 'task.env.defaultJointAngles.joint_2_2=0', 'task.env.defaultJointAngles.joint_2_3=0', 'task.env.desiredJointAngles.joint_1_0=0', 'task.env.desiredJointAngles.joint_1_1=0', 'task.env.desiredJointAngles.joint_1_2=0', 'task.env.desiredJointAngles.joint_1_3=0', 'task.env.desiredJointAngles.joint_2_0=0', 'task.env.desiredJointAngles.joint_2_1=0', 'task.env.desiredJointAngles.joint_2_2=0', 'task.env.desiredJointAngles.joint_2_3=0', 'task.env.terrain.terrainType=plane']

cmd_tokens = [['/home/grl/micromamba/envs/py38/bin/python', '/home/grl/Documents/RobotsMakingRobots/legged_env/envs/train.py', 'task=RobotDog', 'test=True', 'num_envs=2', '', "task.env.urdfAsset.file='RobotDog_top-x-7_bottom-z-9.urdf'", "++task.env.urdfAsset.root='/home/grl/Documents/RobotsMakingRobots/evolutionary_loop/RobotDog/Offspring/RobotDog_top-x-7_bottom-z-9'", 'task.env.baseHeightTarget=0.31445404052734377', 'task.env.baseInitState.pos=[0,0,0.31445404052734377]', 'task.env.baseInitState.rot=[0,0,0,1]', 'task.env.defaultJointAngles.joint_1_0=0', 'task.env.defaultJointAngles.joint_1_1=0', 'task.env.defaultJointAngles.joint_1_2=0', 'task.env.defaultJointAngles.joint_1_3=0', 'task.env.defaultJointAngles.joint_2_0=0', 'task.env.defaultJointAngles.joint_2_1=0', 'task.env.defaultJointAngles.joint_2_2=0', 'task.env.defaultJointAngles.joint_2_3=0', 'task.env.desiredJointAngles.joint_1_0=0', 'task.env.desiredJointAngles.joint_1_1=0', 'task.env.desiredJointAngles.joint_1_2=0', 'task.env.desiredJointAngles.joint_1_3=0', 'task.env.desiredJointAngles.joint_2_0=0', 'task.env.desiredJointAngles.joint_2_1=0', 'task.env.desiredJointAngles.joint_2_2=0', 'task.env.desiredJointAngles.joint_2_3=0', 'task.env.terrain.terrainType=plane']]

cmd_tokens.remove('')
# cmd_tokens = ['/home/grl/repo/micromamba/envs/py38/bin/python', '/home/grl/repo/RobotsMakingRobots/legged_env/envs/train.py', 'task=RobotDog', 'test=True', 'num_envs=2', "task.env.urdfAsset.file='RobotDog_top-y-7_bottom-y-2.urdf'", "++task.env.urdfAsset.root='/home/grl/repo/RobotsMakingRobots/evolutionary_loop/RobotDog/Offspring/RobotDog_top-y-7_bottom-y-2'", 'task.env.baseHeightTarget=0.2794540557861328', 'task.env.baseInitState.pos=[0,0,0.2794540557861328]', 'task.env.baseInitState.rot=[0,0,0,1]', 'task.env.defaultJointAngles.joint_1_0=0', 'task.env.defaultJointAngles.joint_1_1=0', 'task.env.defaultJointAngles.joint_1_2=0', 'task.env.defaultJointAngles.joint_1_3=0', 'task.env.defaultJointAngles.joint_2_0=0', 'task.env.defaultJointAngles.joint_2_1=0', 'task.env.defaultJointAngles.joint_2_2=0', 'task.env.defaultJointAngles.joint_2_3=0', 'task.env.desiredJointAngles.joint_1_0=0', 'task.env.desiredJointAngles.joint_1_1=0', 'task.env.desiredJointAngles.joint_1_2=0', 'task.env.desiredJointAngles.joint_1_3=0', 'task.env.desiredJointAngles.joint_2_0=0', 'task.env.desiredJointAngles.joint_2_1=0', 'task.env.desiredJointAngles.joint_2_2=0', 'task.env.desiredJointAngles.joint_2_3=0', 'task.env.terrain.terrainType=plane']

process = subprocess.Popen(cmd_tokens, stdout=None, stderr=None)
